name: hola mundo

on: 
  workflow_dispatch:  # para que se ejecute de forma manual
  
  schedule: 
    - cron: "*/5 * * * *" # Se ejecuta cada 5 minutos
  
  #push:
   # branches:
    #  - main

jobs: 
  saludar:
    runs-on: ubuntu-latest
    steps: 
      - name: Muestra mensaje hola mundo
        run: echo "Hola mundo Pablo"
        
      - name: Checkout
        uses: actions/checkout@v4.2.2    # obtiene los archivos del repositorio

      - name: Listar los archivos del repositorio
        run: |
          echo "El repositorio ${{ github.repository }} contiene los siguientes archivos: "
          tree
