name: Variables y secretos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Imprmiendo variables y secretos
        run: |
          echo "La variable es ${{ vars.mi_variable }}"
          echo "El secreto es ${{ secrets.CONNECTION_STRING }}"
